# NumPy

NumPy is base library for lot of important libraries such as pandas

NumPy can be considered as evolved brother of list which can store data in upto 3 dimensions

### Why to use NumPy over list? 
1. NumPy is significantly fast when it comes to iteration , because its stores data in very lesser space (bytes) compared to list. 
2. NumPy doesn't do type check in iteration, list checks each value to confirm whther it is int, float,etc. 
3. NumPy has more methods than list
4. NumPy package breaks down a task into multiple fragments and then processes all the fragments parallelly

install NumPy to your python using this package page : https://pypi.org/project/numpy/ 
and import

checkout different data types NumPy supports at https://numpy.org/doc/stable/reference/arrays.dtypes.html


In [3]:
# Import NumPy
import numpy as np

### How to create Numpy arrays
1. Create 1D array

In [4]:
one_d = np.array([1,2,'a',True])
one_d

array(['1', '2', 'a', 'True'], dtype='<U21')

In [5]:
justNumbers = np.array([1,2,45,2.3,-1])
justNumbers

array([ 1. ,  2. , 45. ,  2.3, -1. ])

2. Create 2D array

In [8]:
two_d = np.array([[1,2],[-14,-98.31],[45,-21]])
two_d

array([[  1.  ,   2.  ],
       [-14.  , -98.31],
       [ 45.  , -21.  ]])

3. Create 3D array

In [4]:
three_d = np.array([[[1,'a'],['b',True],[2,'c'],['d',False]],[[1,'a'],['b',True],[-2,'sdf'],[43,'match']]])
three_d

array([[['1', 'a'],
        ['b', 'True'],
        ['2', 'c'],
        ['d', 'False']],

       [['1', 'a'],
        ['b', 'True'],
        ['-2', 'sdf'],
        ['43', 'match']]], dtype='<U21')

4. Create array of random numbers

In [46]:
random = np.random.rand(4,2,3)
random

array([[[0.64444204, 0.67172318, 0.47663596],
        [0.1994177 , 0.03115977, 0.71210657]],

       [[0.09453485, 0.21333913, 0.74680632],
        [0.5240004 , 0.53207296, 0.32630394]],

       [[0.44343122, 0.20808997, 0.46744797],
        [0.87761321, 0.27191356, 0.37919724]],

       [[0.52848473, 0.60781443, 0.66072939],
        [0.12792761, 0.70855209, 0.31951214]]])

🕰️ Create following arrays

1. array of 5 wild animals 
2. array of 5 subjects and their respective difficulty levels (1-5)
3. Create following matrix as array
```
    1,3,4
    5,3,43
    78,65,90
```

### Ways to create numpy array

1. Using List/Tuple

In [13]:
fruits = ['orange','banana','apple','kiwi']

np_fruits = np.array(fruits)
np_fruits

array(['orange', 'banana', 'apple', 'kiwi'], dtype='<U6')

2. based on ranges 
- 1D array `np.arange(starting_num,ending_num,step)`

In [9]:
print('just ending number')
print(np.arange(5))
print('starting and ending number')
print(np.arange(3.2,10))
print('starting and ending number with step')
print(np.arange(3.2,10.2,0.6))

just ending number
[0 1 2 3 4]
starting and ending number
[3.2 4.2 5.2 6.2 7.2 8.2 9.2]
starting and ending number with step
[3.2 3.8 4.4 5.  5.6 6.2 6.8 7.4 8.  8.6 9.2 9.8]


- Equal Intervals `np.linspace(2, 8, 9)`

In [12]:
print('9 Numbers between 2 and 8')
print(np.linspace(2, 8, 9))

9 Numbers between 2 and 8
[2.   2.75 3.5  4.25 5.   5.75 6.5  7.25 8.  ]


- 2D Identity Matrix `np.eye(rows,columns)`

In [14]:
print('Identity Matrix of 4 rows and 4 columns')
print(np.eye(4))
print('Identity Matrix of 3 rows and 4 columns')
print(np.eye(3,4))

Identity Matrix of 4 rows and 4 columns
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Identity Matrix of 3 rows and 4 columns
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


3. Loading CSV data 

`np.loadtxt(csv_path, delimiter, skiprows)` 

In [24]:
print(' 2d array')
print(np.loadtxt('../data/numbers.csv', delimiter = ',') )

 2d array
[[ 20.   111.  ]
 [ 11.   103.  ]
 [ 45.   105.  ]
 [  3.02  98.  ]]


4. Create array with all elements as 0

`np.zeros((row,column))` 

In [26]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

5. Create array with all elements as 1

`np.zeros((row,column))` 

In [27]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### Check basic properties
1. check dimension of array

In [9]:
one_d.ndim

1

In [11]:
two_d.ndim

2

2. check shape

In [12]:
one_d.shape

(4,)

In [13]:
two_d.shape

(3, 2)

In [17]:
three_d.shape

(2, 4, 2)

### Modifying Numpy arrays
1. Accessing elements
Access elemeny by mentioning index number in [row,column] or [row][column] fashion

In [24]:
randomArray = np.array([[1,0,2,9,4,8],[15,23,37,46,18,59]])

In [25]:
randomArray[1][0]

15

In [28]:
randomArray[1,0]

15

🕰️ Can you get 59 number? 

In [39]:
three_d 

array([[['1', 'a'],
        ['b', 'True'],
        ['2', 'c'],
        ['d', 'False']],

       [['1', 'a'],
        ['b', 'True'],
        ['-2', 'sdf'],
        ['43', 'match']]], dtype='<U21')

In [40]:
three_d[1,2,1] # This will work outside in and give us 'sdf'

'sdf'

🕰️ Can you create an array where `nparray[1,0,2] == 'foss4g'` 

Access entire row or column by mentioning index number of other property as ':'


In [32]:
# To get all columns of 1st row
randomArray[0,:]

array([1, 0, 2, 9, 4, 8])

In [33]:
#To get 3rd column of each row
randomArray[:,2]

array([ 2, 37])

2. Updating elements
Update elemet by procividing its index address


In [34]:
randomArray

array([[ 1,  0,  2,  9,  4,  8],
       [15, 23, 37, 46, 18, 59]])

In [35]:
randomArray[1,1] = 2 # 23 will now become 2
randomArray

array([[ 1,  0,  2,  9,  4,  8],
       [15,  2, 37, 46, 18, 59]])

In [37]:
randomArray[1,:] = 4 # Entire 1st index row will become 4
randomArray

array([[1, 0, 2, 9, 4, 8],
       [4, 4, 4, 4, 4, 4]])

In [38]:
randomArray[:,3] = 41 # Entire 3rd index column will become 41
randomArray

array([[ 1,  0,  2, 41,  4,  8],
       [ 4,  4,  4, 41,  4,  4]])

In [42]:
three_d[:,2,:]

array([['2', 'c'],
       ['-2', 'sdf']], dtype='<U21')

In [44]:
three_d[:,2,:] = [['changed', 'yes'],[0,1]] # to replace array, pass another array with same dimension
three_d

array([[['1', 'a'],
        ['b', 'True'],
        ['changed', 'yes'],
        ['d', 'False']],

       [['1', 'a'],
        ['b', 'True'],
        ['0', '1'],
        ['43', 'match']]], dtype='<U21')

🕰️ Create an array of numbers from 1 to 30

1. replace all odd index values with `apple`
2. replace all indexes,multiple of 5 with `cherry`

3. Copying array

In [47]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [48]:
b =a 
b

array([1, 2, 3])

In [49]:
b[0]= 100
b

array([100,   2,   3])

In [50]:
a

array([100,   2,   3])

In [52]:
c= a.copy()
c[0] = 200
c

array([200,   2,   3])

In [53]:
a

array([100,   2,   3])

### Mathematical Operations on Numpy arrays
1. Element wise change

In [55]:
a = np.array([0,1,2,-1])
a

array([ 0,  1,  2, -1])

In [56]:
a + 2

array([2, 3, 4, 1])

In [57]:
a * 3

array([ 0,  3,  6, -3])

In [58]:
b = np.array([9,8,7,6])
b

array([9, 8, 7, 6])

In [59]:
a + b

array([9, 9, 9, 5])

In [60]:
c = np.array([1,2,4])
c

array([1, 2, 4])

In [61]:
a + c # Make sure that both array has same shape 

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [62]:
angles = np.array([30,45,60,90,180])

In [63]:
np.sin(angles) # values are considered as rad

array([-0.98803162,  0.85090352, -0.30481062,  0.89399666, -0.80115264])

In [64]:
np.cos(angles)

array([ 0.15425145,  0.52532199, -0.95241298, -0.44807362, -0.59846007])

In [65]:
np.where(angles> 60)

(array([3, 4]),)

In [78]:
greater_angles = []
for i in np.where(angles> 60)[0]:
    greater_angles.append(angles[i])
greater_angles

[90, 180]

### Axis Numpy arrays
Axis represents how many directions we can go to.

1D array will have single axis viz. axis 0

2D array will have double axis viz. axis 0 (Column), axis 1 (Row)


In [65]:
a = [1,2,3,4]
arr = np.array(a)
arr

array([1, 2, 3, 4])

In [66]:
arr.sum()

10

In [67]:
b = [[1,2,3],[4,5,6],[7,8,9]]
arr_2d = np.array(b)
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
arr_2d.sum(axis=0) # addition will be done vertically

array([12, 15, 18])

In [69]:
arr_2d.sum(axis=1) # addition will be done horizontally

array([ 6, 15, 24])

### Sorting numpy data

In [41]:
random = np.array([1,34,23,54,34,65,90,34,100])

Index of maximum number

In [42]:
random.argmax()

8

Index of minimum number

In [43]:
random.argmin()

0

Index of sorted array

In [44]:
random.argsort()

array([0, 2, 1, 4, 7, 3, 5, 6, 8])

### Reshapeing matrix


In [10]:
ar = np.array([1,2,3,2,45,34])

In [11]:
ar.shape

(6,)

In [12]:
ar.reshape((2,3))

array([[ 1,  2,  3],
       [ 2, 45, 34]])

In [13]:
ar.reshape((1,6))

array([[ 1,  2,  3,  2, 45, 34]])

In [14]:
ar.reshape((2,1,3))

array([[[ 1,  2,  3]],

       [[ 2, 45, 34]]])